language: node_js

jobs:
  include:
    - stage: npm release
      before_deploy:
        - npm ci
        - npm run build:lib
      deploy:
        provider: npm
        email: $EMAIL
        api_key: $API_TOKEN
        cleanup: true
        edge: true
        on:
          tags: true
    - stage: github release
      before_deploy:
        - npm ci
        - npm run build:app
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: ./build/app
        cleanup: true
        keep_history: true
        edge: true
        on:
          branch: master
